### ISSUE TITLE
Make build_auth_request() available through a test module

### ISSUE THREAD

**Issue by Htbaa** [sshaw/Mojolicious-Plugin-DigestAuth#3]
Hi,

I'm currently using your module to quickly add some authentication to a (small) project I'm working on. When I wanted to start writing tests I found out that Mojo::Test (or rather Mojo::UserAgent) doesn't support digest authentication. So testing with this plugin enabled isn't directly possible.

In your `TestHelper` module the function `build_auth_request` fixes this issue, but it's not part of the distribution (it's in the test suite).

I was thinking perhaps it would be a good idea to make the `build_auth_request` function available through some test module so testing can be made easier?

**Comment by sshaw** [comment]
This fell through the cracks but I see that there is a [Mojo::UserAgent::DigestAuth](https://metacpan.org/pod/Mojo::UserAgent::DigestAuth) module now available so I'm going to close this.
